/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pin` | `/pin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/role` | `/role`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(kitchen)'}/queue` | `/queue`; params?: Router.UnknownInputParams; } | { pathname: `${'/(waiter)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(waiter)'}/order` | `/order`; params?: Router.UnknownInputParams; } | { pathname: `${'/(manager)'}/add-staff` | `/add-staff`; params?: Router.UnknownInputParams; } | { pathname: `${'/(manager)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/pin` | `/pin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/role` | `/role`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(kitchen)'}/queue` | `/queue`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(waiter)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(waiter)'}/order` | `/order`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(manager)'}/add-staff` | `/add-staff`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(manager)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/pin${`?${string}` | `#${string}` | ''}` | `/pin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/role${`?${string}` | `#${string}` | ''}` | `/role${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(kitchen)'}/queue${`?${string}` | `#${string}` | ''}` | `/queue${`?${string}` | `#${string}` | ''}` | `${'/(waiter)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(waiter)'}/order${`?${string}` | `#${string}` | ''}` | `/order${`?${string}` | `#${string}` | ''}` | `${'/(manager)'}/add-staff${`?${string}` | `#${string}` | ''}` | `/add-staff${`?${string}` | `#${string}` | ''}` | `${'/(manager)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pin` | `/pin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/role` | `/role`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(kitchen)'}/queue` | `/queue`; params?: Router.UnknownInputParams; } | { pathname: `${'/(waiter)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(waiter)'}/order` | `/order`; params?: Router.UnknownInputParams; } | { pathname: `${'/(manager)'}/add-staff` | `/add-staff`; params?: Router.UnknownInputParams; } | { pathname: `${'/(manager)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
